### ISSUE TITLE
Feature request: Add support for file uploads

### ISSUE THREAD

**Issue by laddi** [runarberg/formsquare#1]
Return data as base64 or Uint8Array.

**Comment by runarberg** [comment]
Note that the [obsolete spec](https://www.w3.org/TR/html-json-forms/) demands file upload support:

> The JSON encoding also supports file uploads. The values of files are themselves structured as objects and contain a type field indicating the MIME type, a name field containing the file name, and a body field with the file's content as base64. 
>
> ### Excample 9: Files ###
>
> ```html
> <form enctype='application/json'>
>   <input type='file' name='file' multiple>
> </form>
> ```
>
> …assuming the user has selected two text files, produces:
>
> ```json
> {
>     "file": [
>         {
>             "type": "text/plain",
>             "name": "dahut.txt",
>             "body": "REFBQUFBQUFIVVVVVVVVVVVVVCEhIQo="
>         },
>         {
>             "type": "text/plain",
>             "name": "litany.txt",
>             "body": "SSBtdXN0IG5vdCBmZWFyLlxuRmVhciBpcyB0aGUgbWluZC1raWxsZXIuCg=="
>         }
>     ]
> }
> ```
