### ISSUE TITLE
Feature request:  Add ability to manually set data type

### ISSUE THREAD

**Issue by laddi** [runarberg/formsquare#3]
For example when you have a `<select>` with values that are all numbers, add the possibility to specify `data-type="number"` so the values would be mapped to the correct data type on parsing.

**Comment by runarberg** [comment]
This is a good idea. We allow custom filtering already, why wouldn’t we allow custom mapping as well? This would however require a change in the API, so I think this belongs to a 1.0.0 milestone

**Comment by laddi** [comment]
Just wanted to remind you of this, had to manually convert data in a form that had either a `type="number"` or `type="hidden"` based on context but should always have been a number.
