### ISSUE TITLE
Feature request: Add flag to be able to only get diff of current and original values

### ISSUE THREAD

**Issue by laddi** [runarberg/formsquare#4]
When you have a form with preset values sometimes it may be beneficial to be able to get the changes to those values only.

**Comment by runarberg** [comment]
Closing since I don’t see a nice and clean way of implementing. Library users can alternatively:

* Use a [deep diff](https://www.npmjs.com/package/deep-diff) between the parsed form object and the old values.
* Mark the changed fields and use a filter `el => el.dataset.changed`.
